# Generated by Django 4.2.27 on 2025-12-21 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0114_workspace_wide_sprints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftissuesprint',
            name='draft_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_issue_sprint', to='db.draftissue'),
        ),
        migrations.AlterField(
            model_name='draftissuesprint',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_issue_sprint', to='db.sprint'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='description',
            field=models.TextField(blank=True, verbose_name='Sprint Description'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Sprint Name'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_sprints', to='db.workspace'),
        ),
        migrations.AlterField(
            model_name='sprintissue',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_sprint', to='db.issue'),
        ),
        migrations.AlterField(
            model_name='sprintissue',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_issues', to='db.sprint'),
        ),
        migrations.AlterField(
            model_name='sprintissue',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_sprint_issues', to='db.workspace'),
        ),
        migrations.AlterField(
            model_name='sprintuserproperties',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_user_properties', to='db.sprint'),
        ),
        migrations.AlterField(
            model_name='sprintuserproperties',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_user_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sprintuserproperties',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_sprint_user_properties', to='db.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together={('workspace', 'number', 'deleted_at')},
        ),
    ]
