# Generated by Django 4.2.21 on 2025-12-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid

import plane.db.models.wiki


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0118_rename_module_id_to_epic_id"),
    ]

    operations = [
        # Ensure pg_trgm extension is available for text search
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),
        migrations.CreateModel(
            name="WikiCollection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=255)),
                (
                    "sort_order",
                    models.FloatField(default=65535),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_collections",
                        to="db.wikicollection",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_collections",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiki Collection",
                "verbose_name_plural": "Wiki Collections",
                "db_table": "wiki_collections",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("description", models.JSONField(blank=True, default=dict)),
                ("description_binary", models.BinaryField(null=True)),
                ("description_html", models.TextField(blank=True, default="<p></p>")),
                ("description_stripped", models.TextField(blank=True, null=True)),
                (
                    "access",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Public"), (1, "Private"), (2, "Shared")],
                        default=1,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "sort_order",
                    models.FloatField(default=65535),
                ),
                (
                    "logo_props",
                    models.JSONField(
                        default=plane.db.models.wiki.get_default_logo_props
                    ),
                ),
                ("archived_at", models.DateField(blank=True, null=True)),
                ("view_props", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_wiki_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="db.wikicollection",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_pages",
                        to="db.wikipage",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_pages",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiki Page",
                "verbose_name_plural": "Wiki Pages",
                "db_table": "wiki_pages",
                "ordering": ("sort_order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="WikiPageShare",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "permission",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "View"), (1, "Edit"), (2, "Admin")],
                        default=0,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="db.wikipage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_page_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_page_shares",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiki Page Share",
                "verbose_name_plural": "Wiki Page Shares",
                "db_table": "wiki_page_shares",
                "ordering": ("-created_at",),
                "unique_together": {("page", "user", "deleted_at")},
            },
        ),
        migrations.CreateModel(
            name="WikiPageVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "last_saved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("description_binary", models.BinaryField(null=True)),
                ("description_html", models.TextField(blank=True, default="<p></p>")),
                ("description_stripped", models.TextField(blank=True, null=True)),
                ("description_json", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_page_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="db.wikipage",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_page_versions",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiki Page Version",
                "verbose_name_plural": "Wiki Page Versions",
                "db_table": "wiki_page_versions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WikiPageAccessLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("edit", "Edit"),
                            ("admin_view", "Admin View"),
                            ("share", "Share"),
                            ("unshare", "Unshare"),
                            ("lock", "Lock"),
                            ("unlock", "Unlock"),
                            ("archive", "Archive"),
                            ("restore", "Restore"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="db.wikipage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_access_logs",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiki Page Access Log",
                "verbose_name_plural": "Wiki Page Access Logs",
                "db_table": "wiki_page_access_logs",
                "ordering": ("-created_at",),
            },
        ),
        # Add indexes for WikiCollection
        migrations.AddIndex(
            model_name="wikicollection",
            index=models.Index(
                fields=["workspace", "parent"], name="wikicoll_ws_parent_idx"
            ),
        ),
        # Add indexes for WikiPage
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["workspace", "collection"], name="wikipage_ws_coll_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["workspace", "parent"], name="wikipage_ws_parent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["workspace", "access"], name="wikipage_ws_access_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["workspace", "owned_by"], name="wikipage_ws_owner_idx"
            ),
        ),
        # Trigram index for full-text search
        migrations.RunSQL(
            sql="""
            CREATE INDEX wikipage_search_idx ON wiki_pages
            USING gin (description_stripped gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS wikipage_search_idx;",
        ),
        # Add indexes for WikiPageShare
        migrations.AddIndex(
            model_name="wikipageshare",
            index=models.Index(
                fields=["page", "user"], name="wikishare_page_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipageshare",
            index=models.Index(
                fields=["user", "permission"], name="wikishare_user_perm_idx"
            ),
        ),
        # Add constraint for WikiPageShare
        migrations.AddConstraint(
            model_name="wikipageshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True),
                fields=("page", "user"),
                name="wiki_page_share_unique_when_not_deleted",
            ),
        ),
        # Add indexes for WikiPageVersion
        migrations.AddIndex(
            model_name="wikipageversion",
            index=models.Index(
                fields=["page", "-created_at"], name="wikiversion_page_date_idx"
            ),
        ),
        # Add indexes for WikiPageAccessLog
        migrations.AddIndex(
            model_name="wikipageaccesslog",
            index=models.Index(
                fields=["page", "-created_at"], name="wikilog_page_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipageaccesslog",
            index=models.Index(
                fields=["user", "-created_at"], name="wikilog_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipageaccesslog",
            index=models.Index(
                fields=["workspace", "access_type"], name="wikilog_ws_type_idx"
            ),
        ),
    ]
