# Generated by Django 4.2 on 2024-12-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0119_wiki_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployboard",
            name="is_roadmap_view",
            field=models.BooleanField(default=False),
        ),
    ]
