# Generated by Django 4.2.27 on 2025-12-24 12:55

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0120_webhook_rename_cycle_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftissueepic',
            options={'ordering': ('-created_at',), 'verbose_name': 'Draft Issue Epic', 'verbose_name_plural': 'Draft Issue Epics'},
        ),
        migrations.AlterModelOptions(
            name='epic',
            options={'ordering': ('-created_at',), 'verbose_name': 'Epic', 'verbose_name_plural': 'Epics'},
        ),
        migrations.AlterModelOptions(
            name='epicissue',
            options={'ordering': ('-created_at',), 'verbose_name': 'Epic Issue', 'verbose_name_plural': 'Epic Issues'},
        ),
        migrations.AlterModelOptions(
            name='epiclink',
            options={'ordering': ('-created_at',), 'verbose_name': 'Epic Link', 'verbose_name_plural': 'Epic Links'},
        ),
        migrations.AlterModelOptions(
            name='epicmember',
            options={'ordering': ('-created_at',), 'verbose_name': 'Epic Member', 'verbose_name_plural': 'Epic Members'},
        ),
        migrations.AlterModelOptions(
            name='epicuserproperties',
            options={'ordering': ('-created_at',), 'verbose_name': 'Epic User Property', 'verbose_name_plural': 'Epic User Properties'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', plane.db.models.user.UserManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='draftissueepic',
            name='module_draft_issue_unique_issue_module_when_deleted_at_null',
        ),
        migrations.RemoveConstraint(
            model_name='epic',
            name='module_unique_name_project_when_deleted_at_null',
        ),
        migrations.RemoveConstraint(
            model_name='epicissue',
            name='module_issue_unique_issue_module_when_deleted_at_null',
        ),
        migrations.RemoveConstraint(
            model_name='epicmember',
            name='module_member_unique_module_member_when_deleted_at_null',
        ),
        migrations.RemoveConstraint(
            model_name='epicuserproperties',
            name='module_user_properties_unique_module_user_when_deleted_at_null',
        ),
        migrations.RemoveField(
            model_name='issueversion',
            name='modules',
        ),
        migrations.AddField(
            model_name='issueversion',
            name='epics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('deactivated', 'Deactivated')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='draftissueepic',
            name='draft_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_issue_epic', to='db.draftissue'),
        ),
        migrations.AlterField(
            model_name='draftissueepic',
            name='epic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_issue_epic', to='db.epic'),
        ),
        migrations.AlterField(
            model_name='epic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Epic Description'),
        ),
        migrations.AlterField(
            model_name='epic',
            name='description_html',
            field=models.JSONField(blank=True, null=True, verbose_name='Epic Description HTML'),
        ),
        migrations.AlterField(
            model_name='epic',
            name='description_text',
            field=models.JSONField(blank=True, null=True, verbose_name='Epic Description RT'),
        ),
        migrations.AlterField(
            model_name='epic',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epic_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='epic',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='epic_members', through='db.EpicMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='epic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Epic Name'),
        ),
        migrations.AlterField(
            model_name='epicissue',
            name='epic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_epic', to='db.epic'),
        ),
        migrations.AlterField(
            model_name='epicissue',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_epic', to='db.issue'),
        ),
        migrations.AlterField(
            model_name='epiclink',
            name='epic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_epic', to='db.epic'),
        ),
        migrations.AlterField(
            model_name='epicuserproperties',
            name='epic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_user_properties', to='db.epic'),
        ),
        migrations.AlterField(
            model_name='epicuserproperties',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_user_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_stripped'], name='wikipage_search_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='draftissueepic',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('draft_issue', 'epic'), name='epic_draft_issue_unique_issue_epic_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='epic',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'project'), name='epic_unique_name_project_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='epicissue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'epic'), name='epic_issue_unique_issue_epic_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='epicmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('epic', 'member'), name='epic_member_unique_epic_member_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='epicuserproperties',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('epic', 'user'), name='epic_user_properties_unique_epic_user_when_deleted_at_null'),
        ),
    ]
