# Generated by Django 4.2.27 on 2025-12-26 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_migrate_invitations_to_shadow_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintMemberProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Sprint Member Project',
                'verbose_name_plural': 'Sprint Member Projects',
                'db_table': 'sprint_member_projects',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='epic_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='intake_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='issue_views_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='network',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Secret'), (2, 'Shared'), (4, 'Public')], default=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='sprint_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='invitation_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sprintmemberproject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='sprintmemberproject',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_project_assignments', to='db.workspacemember'),
        ),
        migrations.AddField(
            model_name='sprintmemberproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_member_assignments', to='db.project'),
        ),
        migrations.AddField(
            model_name='sprintmemberproject',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_member_projects', to='db.sprint'),
        ),
        migrations.AddField(
            model_name='sprintmemberproject',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='sprintmemberproject',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_sprint_member_projects', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='sprintmemberproject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('sprint', 'member'), name='sprint_member_project_unique_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='sprintmemberproject',
            unique_together={('sprint', 'member', 'deleted_at')},
        ),
    ]
