# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove ProjectSprint model.

    Project-sprint relationships are now derived from:
    - SprintMemberProject (who works on which project during which sprint)
    - SprintIssue (which issues are in which sprint)

    See docs/architecture/sprint-project-model.md for details.
    """

    dependencies = [
        ("db", "0124_add_project_sprint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectsprint",
            name="project_sprint_unique_when_deleted_at_null",
        ),
        migrations.DeleteModel(
            name="ProjectSprint",
        ),
    ]
