# Generated by Django 4.2.27 on 2025-12-26 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_remove_project_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='project',
            field=models.ForeignKey(blank=True, help_text="Optional project association. When set, page appears in project's Pages tab.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages', to='db.project'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['workspace', 'project'], name='wikipage_ws_proj_idx'),
        ),
        # Note: wikipage_search_idx already exists from wiki model creation
    ]
