# Generated by Django 4.2.27 on 2025-12-27 01:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import plane.db.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_extend_wiki_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('verb', models.CharField(default='created', max_length=255, verbose_name='Action')),
                ('field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=10)),
                ('old_identifier', models.UUIDField(null=True)),
                ('new_identifier', models.UUIDField(null=True)),
                ('epoch', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Page Activity',
                'verbose_name_plural': 'Page Activities',
                'db_table': 'page_activities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment_stripped', models.TextField(blank=True, verbose_name='Comment')),
                ('comment_json', models.JSONField(blank=True, default=dict)),
                ('comment_html', models.TextField(blank=True, default='<p></p>')),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=10)),
                ('access', models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL')], default='INTERNAL', max_length=100)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Page Comment',
                'verbose_name_plural': 'Page Comments',
                'db_table': 'page_comments',
                'ordering': ('-created_at',),
            },
            bases=(plane.db.mixins.ChangeTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageCommentReaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reaction', models.TextField()),
            ],
            options={
                'verbose_name': 'Page Comment Reaction',
                'verbose_name_plural': 'Page Comment Reactions',
                'db_table': 'page_comment_reactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PageMention',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Page Mention',
                'verbose_name_plural': 'Page Mentions',
                'db_table': 'page_mentions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PageSubscriber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Page Subscriber',
                'verbose_name_plural': 'Page Subscribers',
                'db_table': 'page_subscribers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='pagepropertyvalue',
            unique_together={('page', 'property', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='propertydefinition',
            unique_together={('workspace', 'slug', 'deleted_at')},
        ),
        migrations.AddField(
            model_name='pagesubscriber',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagesubscriber',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='db.wikipage'),
        ),
        migrations.AddField(
            model_name='pagesubscriber',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagesubscriber',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagesubscriber',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_subscribers', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='pagemention',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagemention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_mentions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagemention',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='db.wikipage'),
        ),
        migrations.AddField(
            model_name='pagemention',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagemention',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_mentions', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='pagecommentreaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comment_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecommentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='db.pagecomment'),
        ),
        migrations.AddField(
            model_name='pagecommentreaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagecommentreaction',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagecommentreaction',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comment_reactions', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_comment_description', to='db.description'),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='db.wikipage'),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='db.pagecomment'),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='pageactivity',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageactivity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pageactivity',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='db.wikipage'),
        ),
        migrations.AddField(
            model_name='pageactivity',
            name='page_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_activity', to='db.pagecomment'),
        ),
        migrations.AddField(
            model_name='pageactivity',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pageactivity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_activities', to='db.workspace'),
        ),
        migrations.AddIndex(
            model_name='pagesubscriber',
            index=models.Index(fields=['page'], name='pagesubscriber_page_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesubscriber',
            index=models.Index(fields=['subscriber'], name='pagesubscriber_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagesubscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('page', 'subscriber'), name='page_subscriber_unique_when_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='pagesubscriber',
            unique_together={('page', 'subscriber', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='pagemention',
            index=models.Index(fields=['page'], name='pagemention_page_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemention',
            index=models.Index(fields=['mentioned_user'], name='pagemention_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagemention',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('page', 'mentioned_user'), name='page_mention_unique_when_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='pagemention',
            unique_together={('page', 'mentioned_user', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='pagecommentreaction',
            index=models.Index(fields=['comment'], name='pagecomreact_comment_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagecommentreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('comment', 'actor', 'reaction'), name='page_comment_reaction_unique_when_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='pagecommentreaction',
            unique_together={('comment', 'actor', 'reaction', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='pagecomment',
            index=models.Index(fields=['page', '-created_at'], name='pagecomment_page_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomment',
            index=models.Index(fields=['actor'], name='pagecomment_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomment',
            index=models.Index(fields=['workspace', 'page'], name='pagecomment_ws_page_idx'),
        ),
        migrations.AddIndex(
            model_name='pageactivity',
            index=models.Index(fields=['page', '-created_at'], name='pageactivity_page_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pageactivity',
            index=models.Index(fields=['actor'], name='pageactivity_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='pageactivity',
            index=models.Index(fields=['workspace', 'verb'], name='pageactivity_ws_verb_idx'),
        ),
    ]
