# Generated by Django 4.2.27 on 2025-12-27 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_add_page_comments_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Page Link',
                'verbose_name_plural': 'Page Links',
                'db_table': 'page_links',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PageRelation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('relation_type', models.CharField(choices=[('duplicate', 'Duplicate'), ('relates_to', 'Relates To'), ('blocked_by', 'Blocked By'), ('start_before', 'Start Before'), ('finish_before', 'Finish Before'), ('implemented_by', 'Implemented By')], default='blocked_by', max_length=20, verbose_name='Page Relation Type')),
            ],
            options={
                'verbose_name': 'Page Relation',
                'verbose_name_plural': 'Page Relations',
                'db_table': 'page_relations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='pagerelation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagerelation',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_relations', to='db.wikipage'),
        ),
        migrations.AddField(
            model_name='pagerelation',
            name='related_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_page_relations', to='db.wikipage'),
        ),
        migrations.AddField(
            model_name='pagerelation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagerelation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_relations', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='db.wikipage'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_links', to='db.workspace'),
        ),
        migrations.AddIndex(
            model_name='pagerelation',
            index=models.Index(fields=['page'], name='pagerelation_page_idx'),
        ),
        migrations.AddIndex(
            model_name='pagerelation',
            index=models.Index(fields=['related_page'], name='pagerelation_related_idx'),
        ),
        migrations.AddIndex(
            model_name='pagerelation',
            index=models.Index(fields=['relation_type'], name='pagerelation_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagerelation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('page', 'related_page'), name='page_relation_unique_when_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='pagerelation',
            unique_together={('page', 'related_page', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='pagelink',
            index=models.Index(fields=['page'], name='pagelink_page_idx'),
        ),
    ]
