# Generated by Django 4.2.27 on 2025-12-27

"""
Data Migration: Issue → WikiPage

This migration creates the mapping table for Issue→WikiPage transition.
The actual data migration is handled by the management command:
    python manage.py migrate_issues_to_pages

The migration is split this way because Django migrations using apps.get_model()
can have issues with complex model managers. The management command uses the
actual model classes which work correctly.
"""

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_add_page_relations'),
    ]

    operations = [
        # Create mapping table to track Issue -> WikiPage correspondence
        migrations.CreateModel(
            name='IssueToPageMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_id', models.UUIDField(db_index=True)),
                ('page_id', models.UUIDField(db_index=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_page_mappings', to='db.workspace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'issue_to_page_mappings',
                'verbose_name': 'Issue to Page Mapping',
                'verbose_name_plural': 'Issue to Page Mappings',
            },
        ),
        migrations.AddIndex(
            model_name='issuetopagemapping',
            index=models.Index(fields=['issue_id', 'page_id'], name='issue_page_mapping_idx'),
        ),
    ]
