# Generated by Django 4.2.27 on 2025-12-27 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_migrate_issues_to_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('contract_type', models.CharField(choices=[('idiq', 'IDIQ'), ('bpa', 'BPA'), ('ffp', 'Firm Fixed Price'), ('tm', 'Time & Materials'), ('cpff', 'Cost Plus Fixed Fee'), ('task_order', 'Task Order'), ('call_order', 'Call Order')], default='ffp', max_length=20)),
                ('hierarchy_type', models.CharField(choices=[('master', 'Master Contract'), ('task_order', 'Task Order'), ('call_order', 'Call Order'), ('standalone', 'Standalone')], default='standalone', max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vendor_contact', models.CharField(blank=True, max_length=255)),
                ('ceiling_amount', models.BigIntegerField(default=0, help_text='Maximum contract value in cents (e.g., 10000000 = $100,000)')),
                ('obligated_amount', models.BigIntegerField(default=0, help_text='Committed/obligated funds in cents')),
                ('expended_amount', models.BigIntegerField(default=0, help_text='Actual spend to date in cents')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pop_start', models.DateField(blank=True, help_text='Period of Performance start date', null=True)),
                ('pop_end', models.DateField(blank=True, help_text='Period of Performance end date', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.FloatField(default=65535)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractProjectAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('allocated_amount', models.BigIntegerField(default=0, help_text='Amount allocated from this contract to this project in cents')),
                ('actual_spend', models.BigIntegerField(default=0, help_text='Actual spend against this allocation in cents')),
                ('fiscal_year', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contract Project Allocation',
                'verbose_name_plural': 'Contract Project Allocations',
                'db_table': 'contract_project_allocations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='contractprojectallocation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='db.contract'),
        ),
        migrations.AddField(
            model_name='contractprojectallocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='contractprojectallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_allocations', to='db.project'),
        ),
        migrations.AddField(
            model_name='contractprojectallocation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, help_text='Parent IDIQ/BPA contract for task orders and call orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_contracts', to='db.contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='contract',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='contractprojectallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('contract', 'project', 'fiscal_year'), name='allocation_unique_contract_project_fy_when_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='contractprojectallocation',
            unique_together={('contract', 'project', 'fiscal_year', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('contract_number', ''), _negated=True)), fields=('workspace', 'contract_number'), name='contract_unique_workspace_number_when_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('workspace', 'contract_number', 'deleted_at')},
        ),
    ]
