#!/bin/bash
# Port Manager for Treasury Plane
# Repository: https://github.com/US-Department-of-the-Treasury/plane-treasury
#
# This script manages dynamic port allocation for dev servers and tests.
# It enables running multiple worktrees concurrently without port conflicts.
#
# Usage:
#   source ./scripts/port-manager.sh
#
#   # Get available ports (scans for first free range)
#   get_available_ports
#
#   # Check if ports are already allocated for this worktree
#   load_ports_if_running
#
#   # Write current ports to .dev-ports file
#   save_ports
#
# Port ranges (offset 0-9, each gets 10 ports):
#   Offset 0: web=3000, admin=3001, space=3002, live=3100, api=8000
#   Offset 1: web=3010, admin=3011, space=3012, live=3110, api=8010
#   ...
#   Offset 9: web=3090, admin=3091, space=3092, live=3190, api=8090

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get project root (works from any subdirectory)
get_project_root() {
    git rev-parse --show-toplevel 2>/dev/null || pwd
}

PROJECT_ROOT=$(get_project_root)
DEV_PORTS_FILE="$PROJECT_ROOT/.dev-ports"

# Default base ports
BASE_WEB_PORT=3000
BASE_ADMIN_PORT=3001
BASE_SPACE_PORT=3002
BASE_LIVE_PORT=3100
BASE_API_PORT=8000

# Current ports (set by get_available_ports or load_ports_if_running)
WEB_PORT=""
ADMIN_PORT=""
SPACE_PORT=""
LIVE_PORT=""
API_PORT=""
PORT_OFFSET=""

# Check if a port is in use
is_port_in_use() {
    local port=$1
    lsof -i :"$port" > /dev/null 2>&1
}

# Check if a port is in use by OUR dev server (check .dev-ports from other worktrees)
is_our_port() {
    local port=$1
    # Check if this port matches what's in our .dev-ports file
    if [ -f "$DEV_PORTS_FILE" ]; then
        grep -q "WEB_PORT=$port\|ADMIN_PORT=$port\|SPACE_PORT=$port\|LIVE_PORT=$port\|API_PORT=$port" "$DEV_PORTS_FILE" 2>/dev/null
        return $?
    fi
    return 1
}

# Calculate ports for a given offset
calculate_ports() {
    local offset=$1
    WEB_PORT=$((BASE_WEB_PORT + offset * 10))
    ADMIN_PORT=$((BASE_ADMIN_PORT + offset * 10))
    SPACE_PORT=$((BASE_SPACE_PORT + offset * 10))
    LIVE_PORT=$((BASE_LIVE_PORT + offset * 10))
    API_PORT=$((BASE_API_PORT + offset * 10))
    PORT_OFFSET=$offset
}

# Check if all ports in a range are available
is_range_available() {
    local offset=$1
    calculate_ports "$offset"

    # Check each port
    for port in $WEB_PORT $ADMIN_PORT $SPACE_PORT $LIVE_PORT $API_PORT; do
        if is_port_in_use "$port"; then
            return 1
        fi
    done
    return 0
}

# Find the first available port range
find_available_range() {
    for offset in 0 1 2 3 4 5 6 7 8 9; do
        if is_range_available "$offset"; then
            echo "$offset"
            return 0
        fi
    done
    echo "-1"
    return 1
}

# Load ports from .dev-ports if servers are still running
load_ports_if_running() {
    if [ ! -f "$DEV_PORTS_FILE" ]; then
        return 1
    fi

    # Source the ports file
    source "$DEV_PORTS_FILE"

    # Check if the servers are actually running on these ports
    if is_port_in_use "$WEB_PORT" && is_port_in_use "$API_PORT"; then
        echo -e "${GREEN}Found running servers from this worktree${NC}"
        echo -e "  Web:   http://localhost:$WEB_PORT"
        echo -e "  API:   http://localhost:$API_PORT"
        return 0
    fi

    # Servers not running, clear the ports
    WEB_PORT=""
    ADMIN_PORT=""
    SPACE_PORT=""
    LIVE_PORT=""
    API_PORT=""
    PORT_OFFSET=""
    return 1
}

# Get available ports (either from existing .dev-ports or scan for new range)
get_available_ports() {
    # First, check if we have running servers for this worktree
    if load_ports_if_running; then
        return 0
    fi

    # Find an available range
    local offset
    offset=$(find_available_range)

    if [ "$offset" = "-1" ]; then
        echo -e "${RED}ERROR: No available port ranges found (checked offsets 0-9)${NC}"
        echo -e "${YELLOW}You may have too many concurrent dev servers running.${NC}"
        echo -e "${YELLOW}Run 'lsof -i :3000-3100' to see what's using ports.${NC}"
        return 1
    fi

    calculate_ports "$offset"

    if [ "$offset" -eq 0 ]; then
        echo -e "${GREEN}Using default ports (range 0)${NC}"
    else
        echo -e "${YELLOW}Default ports in use, using port range $offset${NC}"
    fi

    return 0
}

# Save current ports to .dev-ports file
save_ports() {
    if [ -z "$WEB_PORT" ]; then
        echo -e "${RED}ERROR: Ports not set. Call get_available_ports first.${NC}"
        return 1
    fi

    cat > "$DEV_PORTS_FILE" << EOF
# Auto-generated by port-manager.sh
# DO NOT EDIT - this file is managed automatically
# Delete this file to reset port allocation

PORT_OFFSET=$PORT_OFFSET
WEB_PORT=$WEB_PORT
ADMIN_PORT=$ADMIN_PORT
SPACE_PORT=$SPACE_PORT
LIVE_PORT=$LIVE_PORT
API_PORT=$API_PORT

# For convenience in scripts
E2E_BASE_URL=http://localhost:$WEB_PORT
EOF

    echo -e "${GREEN}Saved ports to $DEV_PORTS_FILE${NC}"
}

# Print current port configuration
print_ports() {
    echo ""
    echo -e "${BLUE}Port Configuration:${NC}"
    echo -e "  Offset:  $PORT_OFFSET"
    echo -e "  Web:     http://localhost:$WEB_PORT"
    echo -e "  Admin:   http://localhost:$ADMIN_PORT"
    echo -e "  Space:   http://localhost:$SPACE_PORT"
    echo -e "  Live:    http://localhost:$LIVE_PORT"
    echo -e "  API:     http://localhost:$API_PORT"
    echo ""
}

# Clean up .dev-ports file (call on shutdown)
cleanup_ports() {
    if [ -f "$DEV_PORTS_FILE" ]; then
        rm -f "$DEV_PORTS_FILE"
        echo -e "${GREEN}Cleaned up $DEV_PORTS_FILE${NC}"
    fi
}

# Export environment variables for use by other scripts
export_port_env() {
    export WEB_PORT
    export ADMIN_PORT
    export SPACE_PORT
    export LIVE_PORT
    export API_PORT
    export PORT_OFFSET
    export E2E_BASE_URL="http://localhost:$WEB_PORT"
}
